PC/SC plugin compilation fixed PC/SC Debian package working

diff --git a/gppcscconnectionplugin/configure b/gppcscconnectionplugin/configure
--- a/gppcscconnectionplugin/configure
+++ b/gppcscconnectionplugin/configure
@@ -788,6 +788,10 @@ ac_includes_default="\
 #endif"
 
 ac_subst_vars='LTLIBOBJS
+GLOBALPLATFORM_H_PATH
+GLOBALPLATFORM_CFLAGS
+GLOBALPLATFORM_LIBS
+GLOBALPLATFORM_LIB_PATH
 PCSCLITE_H_PATH
 PCSCLITE_CFLAGS
 PCSCLITE_LIBS
@@ -929,7 +933,11 @@ CPP
 WINSCARD_LIB_PATH
 PCSCLITE_CFLAGS
 PCSCLITE_LIBS
-PCSCLITE_H_PATH'
+PCSCLITE_H_PATH
+GLOBALPLATFORM_LIB_PATH
+GLOBALPLATFORM_CFLAGS
+GLOBALPLATFORM_LIBS
+GLOBALPLATFORM_H_PATH'
 
 
 # Initialize some variables set by options.
@@ -1597,6 +1605,14 @@ Some influential environment variables:
   PCSCLITE_LIBS
               linker flags for PCSCLITE, overriding pkg-config
   PCSCLITE_H_PATH
+              Specifies the location of pcsclite.h for Windows
+  GLOBALPLATFORM_LIB_PATH
+              Specifies the location of GlobalPlatform.lib for Windows
+  GLOBALPLATFORM_CFLAGS
+              C compiler flags for GLOBALPLATFORM, overriding pkg-config
+  GLOBALPLATFORM_LIBS
+              linker flags for GLOBALPLATFORM, overriding pkg-config
+  GLOBALPLATFORM_H_PATH
               Specifies the location of pcsclite.h for Windows
 
 Use these variables to override the choices made by `configure' or to help
@@ -5222,13 +5238,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:5225: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:5241: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:5228: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:5244: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:5231: output\"" >&5)
+  (eval echo "\"\$as_me:5247: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -6431,7 +6447,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6434 "configure"' > conftest.$ac_ext
+  echo '#line 6450 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8046,11 +8062,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8049: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8065: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8053: \$? = $ac_status" >&5
+   echo "$as_me:8069: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8385,11 +8401,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8388: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8404: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8392: \$? = $ac_status" >&5
+   echo "$as_me:8408: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8490,11 +8506,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8493: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8509: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8497: \$? = $ac_status" >&5
+   echo "$as_me:8513: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8545,11 +8561,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8548: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8564: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8552: \$? = $ac_status" >&5
+   echo "$as_me:8568: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11358,7 +11374,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11361 "configure"
+#line 11377 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11454,7 +11470,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11457 "configure"
+#line 11473 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12675,6 +12691,10 @@ fi
 done
 
 
+####################
+#Debug Configuration
+####################
+
 # Check whether --enable-debug was given.
 if test "${enable_debug+set}" = set; then
   enableval=$enable_debug;  case "${enableval}" in
@@ -12698,6 +12718,10 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
 fi
+
+#######################
+#pcsclite Configuration
+#######################
 
 
 
@@ -13063,6 +13087,368 @@ fi
 esac
 LDFLAGS="$OLD_LDFLAGS"
 
+#############################
+#GlobalPlatform Configuration
+#############################
+
+
+
+# Windows must be handled different
+case "$host" in
+*-*-cygwin*)
+	if ! test -f "$GLOBALPLATFORM_LIB_PATH"/GlobalPlatform.lib;
+	  then { { $as_echo "$as_me:$LINENO: error: GlobalPlatform.lib not found, specify location of GlobalPlatform.lib with
+	./configure GLOBALPLATFORM_LIB_PATH=<library directory>" >&5
+$as_echo "$as_me: error: GlobalPlatform.lib not found, specify location of GlobalPlatform.lib with
+	./configure GLOBALPLATFORM_LIB_PATH=<library directory>" >&2;}
+   { (exit 1); exit 1; }; }
+	fi
+	GLOBALPLATFORM_LIBS="-lGlobalPlatform -L"GLOBALPLATFORM_LIB_PATH""
+
+  ;;
+*)
+
+pkg_failed=no
+{ $as_echo "$as_me:$LINENO: checking for GLOBALPLATFORM" >&5
+$as_echo_n "checking for GLOBALPLATFORM... " >&6; }
+
+if test -n "$PKG_CONFIG"; then
+    if test -n "$GLOBALPLATFORM_CFLAGS"; then
+        pkg_cv_GLOBALPLATFORM_CFLAGS="$GLOBALPLATFORM_CFLAGS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"globalplatform >= 6.0.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "globalplatform >= 6.0.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_GLOBALPLATFORM_CFLAGS=`$PKG_CONFIG --cflags "globalplatform >= 6.0.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+if test -n "$PKG_CONFIG"; then
+    if test -n "$GLOBALPLATFORM_LIBS"; then
+        pkg_cv_GLOBALPLATFORM_LIBS="$GLOBALPLATFORM_LIBS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"globalplatform >= 6.0.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "globalplatform >= 6.0.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_GLOBALPLATFORM_LIBS=`$PKG_CONFIG --libs "globalplatform >= 6.0.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        GLOBALPLATFORM_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "globalplatform >= 6.0.0"`
+        else
+	        GLOBALPLATFORM_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "globalplatform >= 6.0.0"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$GLOBALPLATFORM_PKG_ERRORS" >&5
+
+	{ $as_echo "$as_me:$LINENO: result: no" >&5
+$as_echo "no" >&6; }
+
+		{ { $as_echo "$as_me:$LINENO: error: install GlobalPlatform 6.0.0 or later" >&5
+$as_echo "$as_me: error: install GlobalPlatform 6.0.0 or later" >&2;}
+   { (exit 1); exit 1; }; }
+
+
+elif test $pkg_failed = untried; then
+
+		{ { $as_echo "$as_me:$LINENO: error: install GlobalPlatform 6.0.0 or later" >&5
+$as_echo "$as_me: error: install GlobalPlatform 6.0.0 or later" >&2;}
+   { (exit 1); exit 1; }; }
+
+
+else
+	GLOBALPLATFORM_CFLAGS=$pkg_cv_GLOBALPLATFORM_CFLAGS
+	GLOBALPLATFORM_LIBS=$pkg_cv_GLOBALPLATFORM_LIBS
+        { $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+	:
+fi
+  ;;
+esac
+
+
+
+OLD_CFLAGS="$CFLAGS"
+case "$host" in
+*-*-cygwin*)
+	if ! test -f "$GLOBALPLATFORM_H_PATH/globalplatform.h";
+	  then { { $as_echo "$as_me:$LINENO: error: globalplatform.h not found, specify location of globalplatform.h with
+	./configure GLOBALPLATFORM_H_PATH=<include directory>" >&5
+$as_echo "$as_me: error: globalplatform.h not found, specify location of globalplatform.h with
+	./configure GLOBALPLATFORM_H_PATH=<include directory>" >&2;}
+   { (exit 1); exit 1; }; }
+	fi
+	GLOBALPLATFORM_CFLAGS=-I"$GLOBALPLATFORM__H_PATH"
+
+  ;;
+  *)
+    CFLAGS="$CFLAGS $GLOBALPLATFORM_CFLAGS"
+    if test "${ac_cv_header_globalplatform_h+set}" = set; then
+  { $as_echo "$as_me:$LINENO: checking for globalplatform.h" >&5
+$as_echo_n "checking for globalplatform.h... " >&6; }
+if test "${ac_cv_header_globalplatform_h+set}" = set; then
+  $as_echo_n "(cached) " >&6
+fi
+{ $as_echo "$as_me:$LINENO: result: $ac_cv_header_globalplatform_h" >&5
+$as_echo "$ac_cv_header_globalplatform_h" >&6; }
+else
+  # Is the header compilable?
+{ $as_echo "$as_me:$LINENO: checking globalplatform.h usability" >&5
+$as_echo_n "checking globalplatform.h usability... " >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <globalplatform.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval ac_try_echo="\"\$as_me:$LINENO: $ac_try_echo\""
+$as_echo "$ac_try_echo") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  $as_echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ $as_echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+$as_echo "$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ $as_echo "$as_me:$LINENO: checking globalplatform.h presence" >&5
+$as_echo_n "checking globalplatform.h presence... " >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <globalplatform.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval ac_try_echo="\"\$as_me:$LINENO: $ac_try_echo\""
+$as_echo "$ac_try_echo") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  $as_echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ $as_echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+$as_echo "$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { $as_echo "$as_me:$LINENO: WARNING: globalplatform.h: accepted by the compiler, rejected by the preprocessor!" >&5
+$as_echo "$as_me: WARNING: globalplatform.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { $as_echo "$as_me:$LINENO: WARNING: globalplatform.h: proceeding with the compiler's result" >&5
+$as_echo "$as_me: WARNING: globalplatform.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { $as_echo "$as_me:$LINENO: WARNING: globalplatform.h: present but cannot be compiled" >&5
+$as_echo "$as_me: WARNING: globalplatform.h: present but cannot be compiled" >&2;}
+    { $as_echo "$as_me:$LINENO: WARNING: globalplatform.h:     check for missing prerequisite headers?" >&5
+$as_echo "$as_me: WARNING: globalplatform.h:     check for missing prerequisite headers?" >&2;}
+    { $as_echo "$as_me:$LINENO: WARNING: globalplatform.h: see the Autoconf documentation" >&5
+$as_echo "$as_me: WARNING: globalplatform.h: see the Autoconf documentation" >&2;}
+    { $as_echo "$as_me:$LINENO: WARNING: globalplatform.h:     section \"Present But Cannot Be Compiled\"" >&5
+$as_echo "$as_me: WARNING: globalplatform.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { $as_echo "$as_me:$LINENO: WARNING: globalplatform.h: proceeding with the preprocessor's result" >&5
+$as_echo "$as_me: WARNING: globalplatform.h: proceeding with the preprocessor's result" >&2;}
+    { $as_echo "$as_me:$LINENO: WARNING: globalplatform.h: in the future, the compiler will take precedence" >&5
+$as_echo "$as_me: WARNING: globalplatform.h: in the future, the compiler will take precedence" >&2;}
+    ( cat <<\_ASBOX
+## ----------------------------------------- ##
+## Report this to k_o_@users.sourceforge.net ##
+## ----------------------------------------- ##
+_ASBOX
+     ) | sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+{ $as_echo "$as_me:$LINENO: checking for globalplatform.h" >&5
+$as_echo_n "checking for globalplatform.h... " >&6; }
+if test "${ac_cv_header_globalplatform_h+set}" = set; then
+  $as_echo_n "(cached) " >&6
+else
+  ac_cv_header_globalplatform_h=$ac_header_preproc
+fi
+{ $as_echo "$as_me:$LINENO: result: $ac_cv_header_globalplatform_h" >&5
+$as_echo "$ac_cv_header_globalplatform_h" >&6; }
+
+fi
+if test "x$ac_cv_header_globalplatform_h" = x""yes; then
+  :
+else
+  { { $as_echo "$as_me:$LINENO: error: globalplatform.h not found or usable, install GlobalPlatform 6.0.0
+    or later, or use ./configure GLOBALPLATFORM_CFLAGS=-I<include directory>" >&5
+$as_echo "$as_me: error: globalplatform.h not found or usable, install GlobalPlatform 6.0.0
+    or later, or use ./configure GLOBALPLATFORM_CFLAGS=-I<include directory>" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+  ;;
+esac
+CFLAGS="$OLD_CFLAGS"
+
+OLD_LDFLAGS="$LDFLAGS"
+# Windows must be handled different
+case "$host" in
+*-*-cygwin*)
+  ;;
+*)
+	LDFLAGS="$LDFLAGS $GLOBALPLATFORM_LIBS"
+
+{ $as_echo "$as_me:$LINENO: checking for OPGP_VISA2_derive_keys in -lglobalplatform" >&5
+$as_echo_n "checking for OPGP_VISA2_derive_keys in -lglobalplatform... " >&6; }
+if test "${ac_cv_lib_globalplatform_OPGP_VISA2_derive_keys+set}" = set; then
+  $as_echo_n "(cached) " >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lglobalplatform  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char OPGP_VISA2_derive_keys ();
+int
+main ()
+{
+return OPGP_VISA2_derive_keys ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval ac_try_echo="\"\$as_me:$LINENO: $ac_try_echo\""
+$as_echo "$ac_try_echo") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext && {
+	 test "$cross_compiling" = yes ||
+	 $as_test_x conftest$ac_exeext
+       }; then
+  ac_cv_lib_globalplatform_OPGP_VISA2_derive_keys=yes
+else
+  $as_echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_globalplatform_OPGP_VISA2_derive_keys=no
+fi
+
+rm -rf conftest.dSYM
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ $as_echo "$as_me:$LINENO: result: $ac_cv_lib_globalplatform_OPGP_VISA2_derive_keys" >&5
+$as_echo "$ac_cv_lib_globalplatform_OPGP_VISA2_derive_keys" >&6; }
+if test "x$ac_cv_lib_globalplatform_OPGP_VISA2_derive_keys" = x""yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBGLOBALPLATFORM 1
+_ACEOF
+
+  LIBS="-lglobalplatform $LIBS"
+
+else
+  { { $as_echo "$as_me:$LINENO: error: OPGP_VISA2_derive_keys() not found, install GlobalPlatform 6.0.0 or later" >&5
+$as_echo "$as_me: error: OPGP_VISA2_derive_keys() not found, install GlobalPlatform 6.0.0 or later" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+  ;;
+esac
+LDFLAGS="$OLD_LDFLAGS"
+
+######################
+#OpenSSL Configuration
+######################
+
 
 
 
@@ -13305,6 +13691,10 @@ found, install OpenSSL 0.9.7e or later" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
+
+###############
+#Output results
+###############
 
 { $as_echo "$as_me:$LINENO: result: enable debug     : $debug" >&5
 $as_echo "enable debug     : $debug" >&6; }
